import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header style={{ padding: 12, borderBottom: '1px solid #e5e7eb', marginBottom: 12 }}>
          <nav style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
            <a href="/" style={{ fontWeight: 700 }}>
              PT JKL
            </a>
            <a href="/login/sales">Sales Login</a>
            <a href="/sales">Sales Dashboard</a>
            <a href="/marketing">Marketing</a>
            <a href="/admin">Admin</a>
            <a href="/demo.html" target="_blank">
              Demo UI
            </a>
          </nav>
        </header>
        <main style={{ padding: '0 16px' }}>{children}</main>
      </body>
    </html>
  );
}
